---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: time-series
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zookeeper"
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: node03.st:5000/zookeeper:3.7.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2181  # ZK client
          - containerPort: 2888  # Follower
          - containerPort: 3888  # Election
          - containerPort: 8080  # AdminServer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: time-series
  name: main-storage
spec:
  replicas: 5
  selector:
    matchLabels:
      app: time-series-app
  serviceName: "abd-headless-service"
  template:
    metadata:
      labels:
        app: time-series-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: clickhouse-server
        image: node03.st:5000/clickhouse/clickhouse-server:21.8.10.19
        ports:
        - containerPort: 8123  # HTTP Client
        - containerPort: 9000  # TCP Native Client
        - containerPort: 9009  # Inter-Server Replication
        volumeMounts:
        - name: pvc-time-series
          mountPath: /var/lib/clickhouse/
        - name: ch-config
          mountPath: /etc/clickhouse-server/config.yaml
          subPath: config.yaml
        - name: varlog
          mountPath: /var/log
      - name: logger
        image: node03.st:5000/busybox:latest
        args: [/bin/sh, -c, 'tail -n+1 -f /var/log/clickhouse-server/clickhouse-server.log']
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
        - name: varlog
          emptyDir: {}
        - name: ch-config
          configMap:
            name: ch-config
            defaultMode: 0555
            items:
              - key: "config.yaml"
                path: "config.yaml"
  volumeClaimTemplates:
  - metadata:
      name: pvc-time-series
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 150Gi