---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: time-series
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zookeeper"
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: node03.st:5000/zookeeper:3.7.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2181  # ZK client
          - containerPort: 2888  # Follower
          - containerPort: 3888  # Election
          - containerPort: 8080  # AdminServer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: time-series
  name: main-storage
spec:
  replicas: 5
  selector:
    matchLabels:
      app: clickhouse-db
  serviceName: "clickhouse-db-hsvc"
  template:
    metadata:
      labels:
        app: clickhouse-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: clickhouse-server
        image: node03.st:5000/clickhouse/clickhouse-server:21.8.10.19
        ports:
        - containerPort: 8123  # HTTP Client
        - containerPort: 9000  # TCP Native Client
        - containerPort: 9009  # Inter-Server Replication
        volumeMounts:
        - name: varlibclickhouse
          mountPath: /var/lib/clickhouse/
        - name: ch-config
          mountPath: "/etc/clickhouse-server/config.xml"
          readOnly: true
          subPath: "config.xml"
        - name: ch-config
          mountPath: "/etc/clickhouse-server/users.xml"
          readOnly: true
          subPath: "users.xml"
        - name: varlog
          mountPath: /var/log
      - name: logger
        image: node03.st:5000/busybox:latest
        args: [/bin/sh, -c, 'tail -n+1 -f /var/log/clickhouse-server/clickhouse-server.log']
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
        - name: varlibclickhouse
          emptyDir: {}
        - name: varlog
          emptyDir: {}
        - name: ch-config
          configMap:
            name: ch-config
            defaultMode: 0555
            items:
              - key: "config.xml"
                path: "config.xml"
              - key: "users.xml"
                path: "users.xml"
  volumeClaimTemplates:
    - metadata:
        name: pvc-time-series
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 150Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: time-series
  name: clickhouse-db-hsvc
  labels:
    app: clickhouse-db
spec:
  clusterIP: None
  selector:
    app: clickhouse-db
---
apiVersion: v1
kind: Service
metadata:
  namespace: time-series
  name: zookeeper
spec:
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: time-series
  name: ch-config
data:
  config.xml: |
    <yandex>
        <logger>
            <level>trace</level>
            <log>/var/log/clickhouse-server/clickhouse-server.log</log>
            <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
            <size>1000M</size>
            <count>10</count>
        </logger>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <mysql_port>9004</mysql_port>
        <listen_host>::</listen_host>
        <listen_host>0.0.0.0</listen_host>
        <listen_try>1</listen_try>
        <zookeeper incl="zookeeper-servers">
            <node index="1">
                <host>zookeeper-0.zookeeper</host>
                <port>2181</port>
            </node>
        </zookeeper>
        <remote_servers>
            <kube_clickhouse_cluster>
                <shard>
                    <replica>
                        <host>main-storage-0.clickhouse-db-hsvc</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <replica>
                        <host>main-storage-1.clickhouse-db-hsvc</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <replica>
                        <host>main-storage-2.clickhouse-db-hsvc</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <replica>
                        <host>main-storage-3.clickhouse-db-hsvc</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <replica>
                        <host>main-storage-4.clickhouse-db-hsvc</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </kube_clickhouse_cluster>
        </remote_servers>
        <openSSL>
            <server>
                <!--  Used for https server AND secure tcp port  -->
                <!--  openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt  -->
                <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
                <privateKeyFile>/etc/clickhouse-server/server.key</privateKeyFile>
                <!--  openssl dhparam -out /etc/clickhouse-server/dhparam.pem 4096  -->
                <dhParamsFile>/etc/clickhouse-server/dhparam.pem</dhParamsFile>
                <verificationMode>none</verificationMode>
                <loadDefaultCAFile>true</loadDefaultCAFile>
                <cacheSessions>true</cacheSessions>
                <disableProtocols>sslv2,sslv3</disableProtocols>
                <preferServerCiphers>true</preferServerCiphers>
            </server>
            <client>
                <!--  Used for connecting to https dictionary source and secured Zookeeper communication  -->
                <loadDefaultCAFile>true</loadDefaultCAFile>
                <cacheSessions>true</cacheSessions>
                <disableProtocols>sslv2,sslv3</disableProtocols>
                <preferServerCiphers>true</preferServerCiphers>
                <!--  Use for self-signed: <verificationMode>none</verificationMode>  -->
                <invalidCertificateHandler>
                    <!--  Use for self-signed: <name>AcceptCertificateHandler</name>  -->
                    <name>RejectCertificateHandler</name>
                </invalidCertificateHandler>
            </client>
        </openSSL>
        <interserver_http_port>9009</interserver_http_port>
        <!--  Hostname that is used by other replicas to request this server.
                 If not specified, than it is determined analoguous to 'hostname -f' command.
                 This setting could be used to switch replication to another network interface.
               -->
        <!--
            <interserver_http_host>example.yandex.ru</interserver_http_host>
             -->
        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <!--  Maximum number of concurrent queries.  -->
        <max_concurrent_queries>100</max_concurrent_queries>
        <max_server_memory_usage>0</max_server_memory_usage>
        <max_server_memory_usage_to_ram_ratio>0.9</max_server_memory_usage_to_ram_ratio>
        <total_memory_profiler_step>4194304</total_memory_profiler_step>
        <total_memory_tracker_sample_probability>0</total_memory_tracker_sample_probability>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
        <access_control_path>/var/lib/clickhouse/access/</access_control_path>
        <users_config>users.xml</users_config>
        <default_profile>default</default_profile>
        <default_database>default</default_database>
        <mlock_executable>true</mlock_executable>
        <remote_url_allow_hosts>
        </remote_url_allow_hosts>
        <macros incl="macros" optional="true"/>
        <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>
        <max_session_timeout>3600</max_session_timeout>
        <default_session_timeout>60</default_session_timeout>
        <query_log>
            <database>system</database>
            <table>query_log</table>
            <partition_by>toYYYYMM(event_date)</partition_by>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </query_log>
        <trace_log>
            <database>system</database>
            <table>trace_log</table>
            <partition_by>toYYYYMM(event_date)</partition_by>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </trace_log>
        <query_thread_log>
            <database>system</database>
            <table>query_thread_log</table>
            <partition_by>toYYYYMM(event_date)</partition_by>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </query_thread_log>
        <metric_log>
            <database>system</database>
            <table>metric_log</table>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
            <collect_interval_milliseconds>1000</collect_interval_milliseconds>
        </metric_log>
        <asynchronous_metric_log>
            <database>system</database>
            <table>asynchronous_metric_log</table>
            <flush_interval_milliseconds>60000</flush_interval_milliseconds>
        </asynchronous_metric_log>
        <dictionaries_config>*_dictionary.xml</dictionaries_config>
        <compression incl="clickhouse_compression">
            <case>
                <min_part_size>10000000000</min_part_size>
                <min_part_size_ratio>0.01</min_part_size_ratio>
                <method>zstd</method>
            </case>
        </compression>
        <distributed_ddl>
            <path>/clickhouse/task_queue/ddl</path>
        </distributed_ddl>
        <graphite_rollup_example>
            <pattern>
                <regexp>click_cost</regexp>
                <function>any</function>
                <retention>
                    <age>0</age>
                    <precision>3600</precision>
                </retention>
                <retention>
                    <age>86400</age>
                    <precision>60</precision>
                </retention>
            </pattern>
            <default>
                <function>max</function>
                    <retention>
                    <age>0</age>
                    <precision>60</precision>
                </retention>
                <retention>
                    <age>3600</age>
                    <precision>300</precision>
                </retention>
                <retention>
                    <age>86400</age>
                    <precision>3600</precision>
                </retention>
            </default>
        </graphite_rollup_example>
        <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>
        <disable_internal_dns_cache>1</disable_internal_dns_cache>
    </yandex>

  users.xml: |
    <yandex>
        <profiles>
            <default>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
            </default>
            <readonly>
                <readonly>1</readonly>
            </readonly>
        </profiles>
        <users>
            <default>
                <password/>
                <networks incl="networks" replace="replace">
                <ip>::/0</ip>
                </networks>
                <profile>default</profile>
                <quota>default</quota>
            </default>
        </users>
        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </yandex>
